let PMLdata = [
    {
        name: "Liverpool",
        id: 1,
        adress: "liverpool",
        NumberOfPlayers: 22,
        icon: "icon/Liverpool.png",
        TeamValue: 788,
        TeamPower: 95,
        Point : 5,
        Information :"information/Liverpool-information.jpg",
        svd :"svd/Anfield.jpg",
        Stadium :"Anfield"
    },

    {
        name: "ManchesterCity",
        id: 2,
        adress: "manchester",
        NumberOfPlayers: 24,
        icon: "icon/Mancity.png",
        TeamValue: 952,
        TeamPower: 99,
        Point : 3,
        Information :"information/Mancity-information.jpg",
        svd : 'svd/etihad.jpg',
        Stadium : "Etihad"
    },

    {
        name: "ManchesterUtd",
        id: 3,
        adress: "manchester",
        NumberOfPlayers: 24,
        icon: "icon/Manutd.png",
        TeamValue: 788,
        TeamPower: 60,
        Point : 4,
        Information :"information/Manutd-information.jpg",
        svd : 'svd/svd-MU..jpg',
        Stadium:"Old Trafford"
    },

    {
        name: "ChelseaFC",
        id: 4,
        adress: "london",
        NumberOfPlayers: 26,
        icon: "icon/Chelsea.png",
        TeamValue: 766,
        TeamPower: 69,
        Point : 0,
        Information :"information/Chelsea-information.jpg",
        svd : 'svd/svdchelsea.jpg',
        Stadium:"Stamford Bridge"
    },
    {
        name: "TottenhamHospur",
        id: 5,
        adress: "london",
        NumberOfPlayers: 25,
        icon: "icon/Tottenham.png",
        TeamValue: 788,
        TeamPower: 64,
        Point : 0,
        Information :"information/Tottenham-information.jpg",
        svd : 'svd/svdtottenham.jpg',
        Stadium:"Tottenham Stadium"
    }, {
        name: "Arsenal",
        id: 6,
        adress: "london",
        NumberOfPlayers: 25,
        icon: "icon/Asenal.png",
        TeamValue: 498,
        TeamPower: 60,
        Point : 0,
        Information :"information/Arsenal-information.jpg",
        svd : 'svd/svdArsenal.jpg',
        Stadium: "Emirates"
    },
    {
        name: "Everton",
        id: 7,
        adress: "liverpool",
        NumberOfPlayers: 24,
        icon: "icon/Everton.png",
        TeamValue: 350,
        TeamPower: 55,
        Point : 0,
        Information :"information/Everton-information.jpg",
        svd : 'svd/svderverton.jpg',
        Stadium: "Goodison Park"
    },
    {
        name: "Leicester",
        id: 8,
        adress: "leicester",
        NumberOfPlayers: 23,
        icon: "icon/Leiceter.png",
        TeamValue: 287,
        TeamPower: 54,
        Point : 0,
        Information :"information/Leiceter-information.jpg",
        svd : 'svd/Leiceter svd.jpg',
        Stadium: "King Power"
    },
    {
        name: "Westham United",
        id: 9,
        adress: "london",
        NumberOfPlayers: 22,
        icon: "icon/Westham.png",
        TeamValue: 256,
        TeamPower: 50,
        Point : 0,
        Information :"information/Westham-information.jpg",
        svd : 'svd/svdwestham.jpg',
        Stadium: "Olympic Stadium"
    },
    {
        name: "Southamton FC",
        id: 10,
        adress: "southamton",
        NumberOfPlayers: 26,
        icon: "icon/Southampton.png",
        TeamValue: 273,
        TeamPower: 54,
        Point : 0,
        Information :"information/Southampton-information.jpg",
        svd : 'svd/svdsouthamton.jpg',
        Stadium :"StMaryStadium"
    },
    {
        name: "Fullham FC",
        id: 11,
        adress: "liverpool",
        NumberOfPlayers: 22,
        icon: "icon/Fulham.png",
        TeamValue: 218,
        TeamPower: 40,
        Point : 0,
        Information :"information/Fulham-information.jpg",
        svd : 'svd/svdfullham.jpg',
        Stadium:"Craven Cottage"
    },
    {
        name: "Crystal Place",
        id: 12,
        adress: "london",
        NumberOfPlayers: 25,
        icon: "icon/Crystal Place.png",
        TeamValue: 193,
        TeamPower: 54,
        Point : 0,
        Information :"information/Crystal Place-information.jpg",
        svd : 'svd/svd-Crystal Place.jpg',
        Stadium: "Selhurst Park"
    },
    {
        name: "Wolveshamton",
        id: 13,
        adress: "wolve",
        NumberOfPlayers: 25,
        icon: "icon/Wolverhampton.png",
        TeamValue: 172,
        TeamPower: 54,
        Point : 0,
        Information :"information/Wolverhampton-information.jpg",
        svd : 'svd/svdwolveshamton.jpg',
        Stadium:"Molineux"
    },
    {
        name: "Burnley FC",
        id: 14,
        adress: "burnley",
        NumberOfPlayers: 22,
        icon: "icon/Burnley.png",
        TeamValue: 163,
        TeamPower: 44,
        Point : 0,
        Information :"information/Burnley-information.jpg",
        svd : 'svd/svdBurnley.jpg',
        Stadium: "Turf Moor"
    },
    {
        name: "Brighton and Ablion",
        id: 15,
        adress: "brighton",
        NumberOfPlayers: 26,
        icon: "icon/Brighton.png",
        TeamValue: 159,
        TeamPower: 40,
        Point : 0,
        Information :"information/Brighton-information.jpg",
        svd : 'svd/svdBrighton.jpg',
        Stadium: "Falmer Stadium"
    },
    {
        name: "Newcastle United",
        id: 16,
        adress: "sunderland",
        NumberOfPlayers: 22,
        icon: "icon/Newcastle-United.png",
        TeamValue: 156,
        TeamPower: 41,
        Point : 0,
        Information :"information/Newcastle-United-information.jpg",
        svd : 'svd/svdNewcasle.jpg',
        Stadium:"St James' Park"
    },
    {
        name: "Bournemouth FC",
        id: 17,
        adress: "bournemouth",
        NumberOfPlayers: 26,
        icon: "icon/Bouremouth.png",
        TeamValue: 147,
        TeamPower: 39,
        Point : 0,
        Information :"information/Bouremouth-information.jpg",
        svd : 'svd/svdBouthmouht.jpg',
        Stadium:"Dean Court Stadium"
    },
    {
        name: "Watford FC",
        id: 18,
        adress: "watford",
        NumberOfPlayers: 23,
        icon: "icon/Watford.png",
        TeamValue: 144,
        TeamPower: 40,
        Point : 0,
        Information :"information/Watford-information.jpg",
        svd : 'svd/svdWatford.jpg',
        Stadium:"Vicarage Road"
    },
    {
        name: "Huddersfield FC",
        id: 19,
        adress: "hudderfield",
        NumberOfPlayers: 22,
        icon: "icon/Hudderfeild.png",
        TeamValue: 104,
        TeamPower: 38,
        Point : 0,
        Information :"information/Mancity-information.jpg",
        svd : 'svd/svd Huddersfield.jpg',
        Stadium:"Kirklees Stadium"
    },
    {
        name: "Cardiff FC",
        id: 20,
        adress: "cardiff",
        NumberOfPlayers: 23,
        icon: "icon/Cardiff.png",
        TeamValue: 84,
        TeamPower: 38,
        Point : 0,
        Information :"information/Cadiff-information.jpg",
        svd : 'svd/SVD Cardiff.jpg',
        Stadium:"Cardiff City Stadium"
    }
];